// Generated by gen_meta.py
// DO NOT EDIT!

package meta

func init()  {

    RegisterMeta(&C2S_AUTH_TOKEN_Meta{})
    RegisterMeta(&C2S_PING_Meta{})
    RegisterMeta(&S2C_CROSS_DAY_Meta{})
    RegisterMeta(&C2S_CREATE_ROOM_Meta{})
    RegisterMeta(&C2S_ENTER_ROOM_Meta{})
    RegisterMeta(&C2S_SEND_GLOBAL_MSG_Meta{})
    RegisterMeta(&S2C_BROADCAST_ROOM_INFO_Meta{})
    RegisterMeta(&S2C_GLOBAL_MSG_Meta{})

}
